feat(login): improve login UX
hey2022/tls-xb pull request #48
Opened 2024-11-04 08:58 UTC by wusitee

2024-11-04 12:01 UTC, hey2022 requested changes

2024-11-04 13:02 UTC, hey2022 commented on src/main.rs
> +                login().await;
How does one change their login, even if the current one is correct?

2024-11-04 14:30 UTC, aulimaru approved these changes
lgtm

2024-11-04 14:31 UTC, lanbinleo commented
lgtm, and build successfully on windows

2024-11-04 15:11 UTC, hey2022 requested changes

2024-11-04 15:11 UTC, hey2022 commented on src/main.rs
> +    }
```
:: Getting config.toml from /home/yiheng/.config/tls-xb/config.toml...
:: Logging in...
"Name 字段是必需的。"
Sorry, try again.
Username: 123
Password:
"引发类型为“Myth.ErrorException”的异常。"
Sorry, try again.
Username: 123
Password:
"引发类型为“Myth.ErrorException”的异常。"
Sorry, try again.
Username: 20260247
Password:
thread 'main' panicked at src/main.rs:226:5:
3 incorrect login attempts.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
it will prompt for a third login attempt, but it will still fail even if the correct login is inputted

2024-11-05 00:40 UTC, hey2022 requested changes
Otherwise lgtm

2024-11-05 00:40 UTC, hey2022 commented on src/main.rs
> +    while login_times < 3 {
Do we need a while loop, cant we just use a for loop.

2024-11-05 00:40 UTC, hey2022 commented on src/main.rs
> +            }
Why don't we print the error message?

2024-11-05 03:03 UTC, hey2022 approved these changes
lgtm

2024-11-05 03:03 UTC, hey2022 commented
squash merge

2024-11-05 03:06 UTC, merged