Feature GPA full score calculate
hey2022/tls-xb pull request #50
Opened 2024-11-05 07:20 UTC by lanbinleo

Allow user to view the highest GPA score can be obtained

![image](https://github.com/user-attachments/assets/b758085a-626d-4bac-a498-cd4ed7c1757a)

2024-11-05 07:21 UTC, lanbinleo commented
Todo:
- [ ] Update the calculation function, consider electives subjects like chinese and C-Hum
- [ ] Adjust the format of the display, easy to understand (Need a vote or discussion @hey2022 @aulimaru @wusitee )

2024-11-05 07:23 UTC, hey2022 commented
github so fancy can edit by clicking

2024-11-05 07:27 UTC, lanbinleo commented
We got some options. @hey2022 @aulimaru @wusitee 
If they are all kinds of s*it, please give a new design.

![image](https://github.com/user-attachments/assets/95700690-4c20-4699-99cf-8e037f9c5f92)

2024-11-05 07:27 UTC, wusitee commented
For electives and C-Humanity, the weight is already adjusted to 0.5 I think

2024-11-05 07:28 UTC, lanbinleo commented
> For electives and C-Humanity, the weight is already adjusted to 0.5 I think

Okay. I will fix it using weights instead of counting subjects amount

2024-11-05 07:29 UTC, lanbinleo commented
Btw actually this is an potential issue for those who have Chinese and C-Hum:
That our class name is changed to `Chinese II` and `Chinese History` for grade 10s.
![image](https://github.com/user-attachments/assets/cc0ed8c3-9178-4ec5-bc03-2baf8bfb0c29)

2024-11-05 10:21 UTC, hey2022 requested changes

2024-11-05 10:21 UTC, hey2022 commented on src/gpa.rs
> +    false
Do we need to create these functions?

2024-11-05 10:21 UTC, hey2022 commented on src/gpa.rs
> +
Can't we use get_score_mapping_list_id with gpa_from_score to calculate the max GPA?

2024-11-05 10:21 UTC, hey2022 commented on src/main.rs
> +        println!("Unreleased");
```suggestion
        println!("GPA: Unreleased");
```

2024-11-05 11:28 UTC, lanbinleo commented on src/gpa.rs
> +    false
In the beginning, I thought I can reuse this function while calculating total GPA, but then I found that this required `subject_detail` data structure, not `subject`, so I create a new function. Actually you can delete this function, however, I think it may helps to pull this logic out of the service code.

2024-11-05 11:29 UTC, lanbinleo commented on src/gpa.rs
> +
I think you are right, however, I'm not sure what function does `get_score_mapping_list_id` do. I think it is better to add more comments in the code for future development. At least add comments for all the functions.

2024-11-05 13:36 UTC, hey2022 commented on src/gpa.rs
> +    false
I think you can refactor `get_score_mapping_list_id` to take in `subject_name: String` instead of a `&Subject`/`&SubjectDetail`

2024-11-05 13:47 UTC, hey2022 commented on src/gpa.rs
> +
`get_score_mapping_list_id` basically just gets which [score map](https://github.com/hey2022/tls-xb/blob/main/src/score_mapping_configs.json) to use to convert between scores and GPA.

Yes, [doc comments](https://doc.rust-lang.org/rust-by-example/meta/doc.html) should be added to the code.

2024-11-06 07:06 UTC, wusitee commented
How about add a percentage of GPA, like `4.43 / 4.7 (xx%)`

2024-11-06 07:12 UTC, lanbinleo commented
> How about add a percentage of GPA, like `4.43 / 4.7 (xx%)`

Already done in https://github.com/hey2022/tls-xb/pull/50/commits/d14a6cc64f5313d35dbcddc09fb15adb540b007b

2024-11-08 09:29 UTC, wusitee commented on src/gpa.rs
> +
How about consider implementing a method for subject_detail, which might be better (I'm not sure)

2024-11-08 09:31 UTC, wusitee commented on src/gpa.rs
> +
Should follow `src/score_mapping_configs.json` to caculate `total_gpa`.

2024-11-08 10:13 UTC, hey2022 requested changes

2024-11-08 10:13 UTC, hey2022 commented on src/gpa.rs
> +    pub gpa_full: f64,
Can you rename this to max_gpa?

2024-11-08 10:13 UTC, hey2022 commented on src/gpa.rs
> +
You don't need to create a function for this, instead you can make the subject store the ScoreMappingId, and later use it when calculating max GPA like Simon said in his comment.

2024-11-08 10:13 UTC, hey2022 commented on src/gpa.rs
> +
> How about consider implementing a method for subject_detail, which might be better (I'm not sure)

To be honest, I don't think functions should take in a subject detail as a parameter, as it is just a struct that contains incomplete information about a subject.

2024-11-08 10:16 UTC, hey2022 commented on src/gpa.rs
> +
@wusitee didn't select the lines properly, now it's just false...

2024-11-11 06:50 UTC, lanbinleo commented
Simon is assigned to this PR. <3

2024-11-11 06:53 UTC, aulimaru commented
@wusitee Do work

2024-11-12 00:44 UTC, wusitee commented
@hey2022 check check

2024-11-12 02:09 UTC, hey2022 commented on src/gpa.rs
> +        });
Should we use a map sum?

2024-11-12 02:51 UTC, wusitee commented on src/gpa.rs
> +
I don't think it is still needed, since max_gpa is calculated in get_subject function: 
```rust
pub async fn get_subject(
    client: &reqwest::Client,
    semester_id: u64,
    subject_id: u64,
    score_mapping_lists: &HashMap<ScoreMappingId, Vec<ScoreMappingConfig>>,
) -> Subject {
    let subject_detail = get_subject_detail(client, semester_id, subject_id).await;
    let evaluation_projects = get_subject_evaluation_projects(client, &subject_detail).await;
    let total_score = get_subject_score(&evaluation_projects);
    let score_mapping_list_id = get_score_mapping_list_id(&subject_detail);
    let score_mapping_list = &score_mapping_lists[&score_mapping_list_id];
    let gpa = gpa_from_score(total_score, score_mapping_list);
    let max_gpa = gpa_from_score(100.0, score_mapping_list);
    let unweighted_gpa = gpa_from_score(
        total_score,
        &score_mapping_lists[&ScoreMappingId::NonWeighted],
    );
    let score_level = score_level_from_score(total_score, score_mapping_list);
    Subject {
        subject_name: subject_detail.subject_name,
        subject_id,
        class_id: subject_detail.class_id,
        total_score,
        evaluation_projects,
        score_mapping_list_id,
        gpa,
        max_gpa,
        unweighted_gpa,
        score_level,
        elective: false,
        weight: 1.0,
    }
}
```

2024-11-12 05:39 UTC, hey2022 commented on src/gpa.rs
> +
Can you refactor this as well as the other calculate GPA functions?

2024-11-12 10:03 UTC, hey2022 approved these changes
LGTM, rebase onto main,

2024-11-12 10:11 UTC, merged